# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_auto_20161021_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='getornonemodel_ptr',
        ),
        migrations.AddField(
            model_name='artist',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
