# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0003_auto_20161021_1039'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetOrNoneModel',
        ),
    ]
